import localFont from 'next/font/local';
import { HeroUIProvider } from "@heroui/react";
import './globals.css';

const geistSans = localFont({
    src: './fonts/GeistVF.woff',
    variable: '--font-geist-sans',
    weight: '100 900',
});

export const metadata = {
    title: 'Shope - Home',
    description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body>
                <HeroUIProvider>{children}</HeroUIProvider>
            </body>
        </html>
    );
}
