import localFont from 'next/font/local';
import { NextUIProvider } from '@nextui-org/react';
import './globals.css';

const geistSans = localFont({
    src: './fonts/GeistVF.woff',
    variable: '--font-geist-sans',
    weight: '100 900',
});

export const metadata = {
    title: 'Shope - Home',
    description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body>
                <NextUIProvider>{children}</NextUIProvider>
            </body>
        </html>
    );
}
